<?php
/**
 * Zanna Gls Weblabeling Module
 *
 * @author                Zanna Bianca
 * @package             Zanna Gls
 * @version               1.0.0
 * @copyright           2022 Zanna Bianca
 * @license                http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$results = $block->getTrackingInfo();
?>
<style type="text/css">
    .page-main {
        padding: 0 !important;
    }
</style>
<div class="page tracking">
    <?php if (!empty($results)) : ?>
        <?php foreach ($results as $shipId => $result) : ?>
            <?php if (!empty($result)) : ?>
                <?php foreach ($result as $counter => $track) : ?>
                        <?php switch ($block->getType($track)) {
                            default:
                                echo $block->getHtmlTrack($track);
                                break;
                        } ?>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
